/* ✅ UPDATED: moved from inline script in coral-snorkeling-phu-quoc.html */
document.addEventListener('DOMContentLoaded', function () {  var backButton = document.getElementById('snorkelingBackButton'); /* ✅ NEW */
  var heroVideo = document.getElementById('snorkelingHeroVideo'); /* ✅ NEW */
  var bookingModal = document.getElementById('snorkelingBookingModal'); /* ✅ NEW */
  var prepModal = document.getElementById('snorkelingPrepModal'); /* ✅ NEW */
  var bookingForm = document.getElementById('snorkelingBookingForm'); /* ✅ NEW */
  var bookingDate = document.getElementById('bookingDate'); /* ✅ NEW */
  var bookingGuests = document.getElementById('bookingGuests'); /* ✅ NEW */
  var bookingExperience = document.getElementById('bookingExperience'); /* ✅ NEW */
  var bookingName = document.getElementById('bookingName'); /* ✅ NEW */
  var bookingContact = document.getElementById('bookingContact'); /* ✅ NEW */
  var bookingWarning = document.getElementById('bookingWarning'); /* ✅ NEW */
  var bookingSummary = document.getElementById('bookingSummary'); /* ✅ NEW */
  var snorkelingConfirmation = document.getElementById('snorkelingConfirmation'); /* ✅ NEW */
  var swipeStartX = 0; /* ✅ NEW */
  var swipeStartY = 0; /* ✅ NEW */
  var swipeTracking = false; /* ✅ NEW */
  function goBackHome() { window.location.href = 'index.html'; } /* ✅ NEW */
  function openModal(modal) { if (!modal) return; modal.classList.add('is-open'); modal.setAttribute('aria-hidden', 'false'); document.documentElement.style.overflow = 'hidden'; document.body.style.overflow = 'hidden'; } /* ✅ NEW */
  function closeModal(modal) { if (!modal) return; modal.classList.remove('is-open'); modal.setAttribute('aria-hidden', 'true'); document.documentElement.style.overflow = ''; document.body.style.overflow = ''; } /* ✅ NEW */
  function setTomorrowMinDate() { if (!bookingDate) return; var tomorrow = new Date(); tomorrow.setDate(tomorrow.getDate() + 1); bookingDate.min = tomorrow.getFullYear() + '-' + ('0' + (tomorrow.getMonth() + 1)).slice(-2) + '-' + ('0' + tomorrow.getDate()).slice(-2); } /* ✅ NEW */
  function getPackagePrice(type, guests) { if (type === 'diving') { if (guests > 10) return null; return guests <= 5 ? '15,000,000 VND' : '28,000,000 VND'; } if (guests <= 5) return '10,000,000 VND'; if (guests <= 10) return '19,000,000 VND'; return '18,000,000 VND'; } /* ✅ NEW */
  function updateBookingState() { if (!bookingGuests || !bookingExperience || !bookingWarning || !bookingSummary) return; var guests = Number(bookingGuests.value || 0); var type = bookingExperience.value; var price = getPackagePrice(type, guests); var submitButton = bookingForm ? bookingForm.querySelector('button[type="submit"]') : null; if (type === 'diving' && guests > 10) { bookingWarning.textContent = 'Diving is available for up to 10 guests.'; bookingWarning.classList.add('is-visible'); bookingSummary.textContent = 'Please reduce guest count or choose snorkeling.'; if (submitButton) submitButton.disabled = true; return; } bookingWarning.textContent = ''; bookingWarning.classList.remove('is-visible'); bookingSummary.textContent = 'Estimated package: ' + price + ' · All included · Deposit required to confirm.'; if (submitButton) submitButton.disabled = false; } /* ✅ NEW */
  function handleBookingSubmit(event) { event.preventDefault(); updateBookingState(); if (!bookingForm || !snorkelingConfirmation || (bookingForm.querySelector('button[type="submit"]') || {}).disabled) return; var payment = bookingForm.querySelector('input[name="payment"]:checked'); snorkelingConfirmation.innerHTML = '<strong>Booking summary</strong><br>' + 'Date: ' + (bookingDate ? bookingDate.value : '') + '<br>' + 'Guests: ' + (bookingGuests ? bookingGuests.value : '') + '<br>' + 'Experience: ' + (bookingExperience ? bookingExperience.value : '') + '<br>' + 'Name: ' + (bookingName ? bookingName.value : '') + '<br>' + 'Contact: ' + (bookingContact ? bookingContact.value : '') + '<br>' + 'Payment: ' + (payment ? payment.value : 'paypal') + '<br><br>' + 'Placeholder policy: booking is confirmed after deposit. Refund policy will be updated later.'; snorkelingConfirmation.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); } /* ✅ NEW */
  function lazyLoadHeroVideo() { if (!heroVideo) return; var source = heroVideo.querySelector('source[data-src]'); if (!source || !source.getAttribute('data-src')) return; source.src = source.getAttribute('data-src'); heroVideo.load(); heroVideo.addEventListener('canplay', function () { heroVideo.classList.add('is-loaded'); heroVideo.play().catch(function () {}); }, { once: true }); } /* ✅ NEW */
  function isInteractiveTarget(target) { return !!(target && target.closest && target.closest('button, a, input, select, textarea, label, .snorkeling-modal')); } /* ✅ NEW */
  function handleSwipeStart(event) { if (!event.touches || event.touches.length !== 1) return; if (isInteractiveTarget(event.target)) return; if (event.touches[0].clientX > 20) return; swipeTracking = true; swipeStartX = event.touches[0].clientX; swipeStartY = event.touches[0].clientY; } /* ✅ NEW */
  function handleSwipeEnd(event) { if (!swipeTracking || !event.changedTouches || event.changedTouches.length !== 1) return; var deltaX = event.changedTouches[0].clientX - swipeStartX; var deltaY = event.changedTouches[0].clientY - swipeStartY; swipeTracking = false; if (deltaX > 60 && Math.abs(deltaX) > Math.abs(deltaY) * 1.45) goBackHome(); } /* ✅ NEW */
  document.body.classList.add('is-ready'); setTomorrowMinDate(); updateBookingState(); window.setTimeout(lazyLoadHeroVideo, 280); if (backButton) backButton.addEventListener('click', goBackHome); document.querySelectorAll('[data-open-booking]').forEach(function (button) { button.addEventListener('click', function () { openModal(bookingModal); }); }); document.querySelectorAll('[data-open-prep]').forEach(function (button) { button.addEventListener('click', function () { openModal(prepModal); }); }); document.querySelectorAll('[data-close-booking]').forEach(function (button) { button.addEventListener('click', function () { closeModal(bookingModal); }); }); document.querySelectorAll('[data-close-prep]').forEach(function (button) { button.addEventListener('click', function () { closeModal(prepModal); }); }); if (bookingModal) bookingModal.addEventListener('click', function (event) { if (event.target === bookingModal) closeModal(bookingModal); }); if (prepModal) prepModal.addEventListener('click', function (event) { if (event.target === prepModal) closeModal(prepModal); }); if (bookingGuests) bookingGuests.addEventListener('input', updateBookingState); if (bookingExperience) bookingExperience.addEventListener('change', updateBookingState); if (bookingForm) bookingForm.addEventListener('submit', handleBookingSubmit); document.addEventListener('touchstart', handleSwipeStart, { passive: true }); document.addEventListener('touchend', handleSwipeEnd, { passive: true }); document.addEventListener('keydown', function (event) { if (event.key !== 'Escape') return; closeModal(bookingModal); closeModal(prepModal); });
});